services:
  - type: web
    name: resume-screener
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000